[project]
name = "advocatediarysystem"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Arid-P", email = "aridamanpatel.srijan@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "aiosqlite>=0.22.1",
    "fastapi>=0.141.1",
    "pydantic>=2.13.5",
    "sqlalchemy>=2.0.54",
    "uvicorn>=0.53.0",
]

[project.scripts]
advocatediarysystem = "advocatediarysystem:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
